[[redirects]]
  from = "/api/*"
  to = "https://api.myimg.ai/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
